-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HLS_CISR_spmv_accel is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    cmd_start : IN STD_LOGIC_VECTOR (0 downto 0);
    inp_vec_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    inp_vec_ce0 : OUT STD_LOGIC;
    inp_vec_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    slot_data_arr_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    slot_data_arr_ce0 : OUT STD_LOGIC;
    slot_data_arr_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    slot_arr_row_len_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    slot_arr_row_len_ce0 : OUT STD_LOGIC;
    slot_arr_row_len_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_vec_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_vec_ce0 : OUT STD_LOGIC;
    output_vec_we0 : OUT STD_LOGIC;
    output_vec_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of HLS_CISR_spmv_accel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "HLS_CISR_spmv_accel_HLS_CISR_spmv_accel,hls_ip_2020_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=27,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1713,HLS_SYN_LUT=2355,HLS_VERSION=2020_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (25 downto 0) := "00000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (25 downto 0) := "00000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (25 downto 0) := "00000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (25 downto 0) := "00000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (25 downto 0) := "00000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (25 downto 0) := "00000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (25 downto 0) := "00001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (25 downto 0) := "00010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (25 downto 0) := "00100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (25 downto 0) := "01000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (25 downto 0) := "10000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv60_0 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal max_row_id : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal row_len_slot_arr_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal row_len_slot_arr_ce0 : STD_LOGIC;
    signal row_len_slot_arr_we0 : STD_LOGIC;
    signal row_len_slot_arr_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal row_len_slot_arr_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal row_len_slot_arr_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal row_len_slot_arr_ce1 : STD_LOGIC;
    signal row_len_slot_arr_we1 : STD_LOGIC;
    signal row_len_slot_arr_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal row_len_slot_arr_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal slot_counter_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_counter_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_counter_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_counter_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_row_counter_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_res_arr_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_row_len_id_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_row_id_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal slot_row_counter_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_res_arr_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_row_len_id_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_row_id_1 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal slot_row_counter_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_res_arr_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_row_len_id_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_row_id_2 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal slot_row_counter_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_res_arr_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_row_len_id_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal slot_row_id_3 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal reg_640 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal grp_fu_592_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_644 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal cmd_start_read_read_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln26_fu_652_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln53_fu_792_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln53_reg_1378 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln80_fu_914_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_reg_1413 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln80_1_fu_962_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_1_reg_1425 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal icmp_ln80_2_fu_1021_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_2_reg_1437 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal icmp_ln80_3_fu_1080_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_3_reg_1449 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal add_ln92_3_fu_1123_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln107_fu_1165_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln107_reg_1473 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal trunc_ln107_1_fu_1186_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln107_1_reg_1488 : STD_LOGIC_VECTOR (31 downto 0);
    signal matrix_val_fu_1195_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln111_fu_1199_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln107_2_fu_1204_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln107_2_reg_1513 : STD_LOGIC_VECTOR (31 downto 0);
    signal matrix_val_1_fu_1213_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln111_1_fu_1217_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln107_3_fu_1222_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln107_3_reg_1538 : STD_LOGIC_VECTOR (31 downto 0);
    signal matrix_val_2_fu_1231_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln111_2_fu_1235_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_596_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_reg_1558 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal matrix_val_3_fu_1240_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln111_3_fu_1244_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_1_i_reg_1576 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal mul_2_i_reg_1584 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal mul_3_i_reg_1592 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal slot_id_reg_387 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln26_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_row_id_flag_0_reg_398 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_row_id_loc_0_reg_412 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_max_row_id_flag_1_phi_fu_427_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_row_id_flag_1_reg_424 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln92_fu_946_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_max_row_id_new_1_phi_fu_440_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_row_id_new_1_reg_436 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_max_row_id_loc_1_phi_fu_451_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_row_id_loc_1_reg_448 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_15_reg_459 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_max_row_id_flag_2_phi_fu_473_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_row_id_flag_2_reg_470 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln92_1_fu_1005_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_max_row_id_new_2_phi_fu_485_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_row_id_new_2_reg_482 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_max_row_id_loc_2_phi_fu_496_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_row_id_loc_2_reg_493 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_16_reg_504 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_max_row_id_flag_3_phi_fu_518_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_row_id_flag_3_reg_515 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln92_2_fu_1064_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_max_row_id_new_3_phi_fu_530_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_row_id_new_3_reg_527 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_max_row_id_loc_3_phi_fu_541_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_row_id_loc_3_reg_538 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_17_reg_549 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_row_id_new_4_reg_560 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_18_reg_571 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_max_row_id_flag_4_phi_fu_584_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_row_id_flag_4_reg_580 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln37_fu_672_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_fu_683_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln58_fu_800_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln58_1_fu_831_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln58_2_fu_862_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln58_3_fu_893_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln86_fu_924_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln86_1_fu_982_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln86_2_fu_1041_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln86_3_fu_1100_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln111_fu_1169_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln111_1_fu_1190_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln111_2_fu_1208_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln111_3_fu_1226_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln131_fu_1279_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln131_1_fu_1299_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln131_2_fu_1319_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln131_3_fu_1339_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state26 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state26 : signal is "none";
    signal add_ln59_fu_805_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln29_fu_692_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln59_1_fu_836_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln59_2_fu_867_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln59_3_fu_898_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln115_fu_1129_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln87_fu_929_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln115_1_fu_1141_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln87_1_fu_987_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln80_fu_954_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln115_2_fu_1153_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln87_2_fu_1046_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln80_1_fu_1013_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln115_3_fu_1174_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal add_ln87_3_fu_1105_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln80_2_fu_1072_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal bitcast_ln131_fu_1284_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln131_1_fu_1304_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln131_2_fu_1324_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln131_3_fu_1344_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_592_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_592_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_596_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_596_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_664_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln37_fu_677_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln58_fu_821_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln58_fu_825_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln58_1_fu_852_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal xor_ln58_fu_856_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln58_2_fu_883_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln58_1_fu_887_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln86_fu_972_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln86_fu_976_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln86_1_fu_1031_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal xor_ln86_fu_1035_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln86_2_fu_1090_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln86_1_fu_1094_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_630_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component HLS_CISR_spmv_accel_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component HLS_CISR_spmv_accel_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component HLS_CISR_spmv_accel_row_len_slot_arr IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    row_len_slot_arr_U : component HLS_CISR_spmv_accel_row_len_slot_arr
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => row_len_slot_arr_address0,
        ce0 => row_len_slot_arr_ce0,
        we0 => row_len_slot_arr_we0,
        d0 => row_len_slot_arr_d0,
        q0 => row_len_slot_arr_q0,
        address1 => row_len_slot_arr_address1,
        ce1 => row_len_slot_arr_ce1,
        we1 => row_len_slot_arr_we1,
        d1 => row_len_slot_arr_d1,
        q1 => row_len_slot_arr_q1);

    fadd_32ns_32ns_32_5_full_dsp_1_U1 : component HLS_CISR_spmv_accel_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_592_p0,
        din1 => grp_fu_592_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_592_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U2 : component HLS_CISR_spmv_accel_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_596_p0,
        din1 => grp_fu_596_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_596_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    empty_15_reg_459_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln80_fu_914_p2 = ap_const_lv1_0))) then 
                empty_15_reg_459 <= slot_row_counter_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln80_reg_1413 = ap_const_lv1_1))) then 
                empty_15_reg_459 <= row_len_slot_arr_q0;
            end if; 
        end if;
    end process;

    empty_16_reg_504_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_1_fu_962_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                empty_16_reg_504 <= slot_row_counter_1;
            elsif (((icmp_ln80_1_reg_1425 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                empty_16_reg_504 <= row_len_slot_arr_q1;
            end if; 
        end if;
    end process;

    empty_17_reg_549_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_2_fu_1021_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                empty_17_reg_549 <= slot_row_counter_2;
            elsif (((icmp_ln80_2_reg_1437 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                empty_17_reg_549 <= row_len_slot_arr_q0;
            end if; 
        end if;
    end process;

    empty_18_reg_571_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_3_fu_1080_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                empty_18_reg_571 <= slot_row_counter_3;
            elsif (((icmp_ln80_3_reg_1449 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                empty_18_reg_571 <= row_len_slot_arr_q1;
            end if; 
        end if;
    end process;

    max_row_id_flag_0_reg_398_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (cmd_start_read_read_fu_132_p2 = ap_const_lv1_1))) then 
                max_row_id_flag_0_reg_398 <= ap_const_lv1_1;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (cmd_start_read_read_fu_132_p2 = ap_const_lv1_0))) then 
                max_row_id_flag_0_reg_398 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    max_row_id_flag_1_reg_424_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln80_fu_914_p2 = ap_const_lv1_0))) then 
                max_row_id_flag_1_reg_424 <= max_row_id_flag_0_reg_398;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln80_reg_1413 = ap_const_lv1_1))) then 
                max_row_id_flag_1_reg_424 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    max_row_id_flag_2_reg_470_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_1_fu_962_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                max_row_id_flag_2_reg_470 <= ap_phi_mux_max_row_id_flag_1_phi_fu_427_p4;
            elsif (((icmp_ln80_1_reg_1425 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                max_row_id_flag_2_reg_470 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    max_row_id_flag_3_reg_515_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_2_fu_1021_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                max_row_id_flag_3_reg_515 <= ap_phi_mux_max_row_id_flag_2_phi_fu_473_p4;
            elsif (((icmp_ln80_2_reg_1437 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                max_row_id_flag_3_reg_515 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    max_row_id_flag_4_reg_580_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_3_fu_1080_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                max_row_id_flag_4_reg_580 <= ap_phi_mux_max_row_id_flag_3_phi_fu_518_p4;
            elsif (((icmp_ln80_3_reg_1449 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                max_row_id_flag_4_reg_580 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    max_row_id_loc_0_reg_412_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (cmd_start_read_read_fu_132_p2 = ap_const_lv1_1))) then 
                max_row_id_loc_0_reg_412 <= ap_const_lv32_0;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (cmd_start_read_read_fu_132_p2 = ap_const_lv1_0))) then 
                max_row_id_loc_0_reg_412 <= max_row_id;
            end if; 
        end if;
    end process;

    max_row_id_loc_1_reg_448_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln80_fu_914_p2 = ap_const_lv1_0))) then 
                max_row_id_loc_1_reg_448 <= max_row_id_loc_0_reg_412;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln80_reg_1413 = ap_const_lv1_1))) then 
                max_row_id_loc_1_reg_448 <= add_ln92_fu_946_p2;
            end if; 
        end if;
    end process;

    max_row_id_loc_2_reg_493_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_1_fu_962_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                max_row_id_loc_2_reg_493 <= ap_phi_mux_max_row_id_loc_1_phi_fu_451_p4;
            elsif (((icmp_ln80_1_reg_1425 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                max_row_id_loc_2_reg_493 <= add_ln92_1_fu_1005_p2;
            end if; 
        end if;
    end process;

    max_row_id_loc_3_reg_538_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_2_fu_1021_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                max_row_id_loc_3_reg_538 <= ap_phi_mux_max_row_id_loc_2_phi_fu_496_p4;
            elsif (((icmp_ln80_2_reg_1437 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                max_row_id_loc_3_reg_538 <= add_ln92_2_fu_1064_p2;
            end if; 
        end if;
    end process;

    max_row_id_new_1_reg_436_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln80_fu_914_p2 = ap_const_lv1_0))) then 
                max_row_id_new_1_reg_436 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln80_reg_1413 = ap_const_lv1_1))) then 
                max_row_id_new_1_reg_436 <= add_ln92_fu_946_p2;
            end if; 
        end if;
    end process;

    max_row_id_new_2_reg_482_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_1_fu_962_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                max_row_id_new_2_reg_482 <= ap_phi_mux_max_row_id_new_1_phi_fu_440_p4;
            elsif (((icmp_ln80_1_reg_1425 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                max_row_id_new_2_reg_482 <= add_ln92_1_fu_1005_p2;
            end if; 
        end if;
    end process;

    max_row_id_new_3_reg_527_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_2_fu_1021_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                max_row_id_new_3_reg_527 <= ap_phi_mux_max_row_id_new_2_phi_fu_485_p4;
            elsif (((icmp_ln80_2_reg_1437 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                max_row_id_new_3_reg_527 <= add_ln92_2_fu_1064_p2;
            end if; 
        end if;
    end process;

    max_row_id_new_4_reg_560_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_3_fu_1080_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                max_row_id_new_4_reg_560 <= ap_phi_mux_max_row_id_new_3_phi_fu_530_p4;
            elsif (((icmp_ln80_3_reg_1449 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                max_row_id_new_4_reg_560 <= add_ln92_3_fu_1123_p2;
            end if; 
        end if;
    end process;

    slot_counter_0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_0) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_counter_0 <= ap_const_lv32_0;
            elsif (((grp_fu_624_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                slot_counter_0 <= add_ln59_fu_805_p2;
            end if; 
        end if;
    end process;

    slot_counter_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_1) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_counter_1 <= ap_const_lv32_0;
            elsif (((grp_fu_624_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                slot_counter_1 <= add_ln59_1_fu_836_p2;
            end if; 
        end if;
    end process;

    slot_counter_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_2) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_counter_2 <= ap_const_lv32_0;
            elsif (((grp_fu_624_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                slot_counter_2 <= add_ln59_2_fu_867_p2;
            end if; 
        end if;
    end process;

    slot_counter_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_3) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_counter_3 <= ap_const_lv32_0;
            elsif (((grp_fu_624_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                slot_counter_3 <= add_ln59_3_fu_898_p2;
            end if; 
        end if;
    end process;

    slot_id_reg_387_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (cmd_start_read_read_fu_132_p2 = ap_const_lv1_1))) then 
                slot_id_reg_387 <= ap_const_lv3_0;
            elsif (((icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_id_reg_387 <= add_ln26_fu_652_p2;
            end if; 
        end if;
    end process;

    slot_res_arr_0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((trunc_ln29_fu_692_p1 = ap_const_lv2_0) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln80_fu_914_p2 = ap_const_lv1_1)))) then 
                slot_res_arr_0 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
                slot_res_arr_0 <= reg_644;
            end if; 
        end if;
    end process;

    slot_res_arr_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((trunc_ln29_fu_692_p1 = ap_const_lv2_1) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln80_1_fu_962_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8)))) then 
                slot_res_arr_1 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
                slot_res_arr_1 <= reg_644;
            end if; 
        end if;
    end process;

    slot_res_arr_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((trunc_ln29_fu_692_p1 = ap_const_lv2_2) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln80_2_fu_1021_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
                slot_res_arr_2 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
                slot_res_arr_2 <= reg_644;
            end if; 
        end if;
    end process;

    slot_res_arr_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((trunc_ln29_fu_692_p1 = ap_const_lv2_3) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln80_3_fu_1080_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
                slot_res_arr_3 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
                slot_res_arr_3 <= reg_644;
            end if; 
        end if;
    end process;

    slot_row_counter_0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_0) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_row_counter_0 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                slot_row_counter_0 <= add_ln115_fu_1129_p2;
            end if; 
        end if;
    end process;

    slot_row_counter_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_1) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_row_counter_1 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                slot_row_counter_1 <= add_ln115_1_fu_1141_p2;
            end if; 
        end if;
    end process;

    slot_row_counter_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_2) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_row_counter_2 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                slot_row_counter_2 <= add_ln115_2_fu_1153_p2;
            end if; 
        end if;
    end process;

    slot_row_counter_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_3) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_row_counter_3 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                slot_row_counter_3 <= add_ln115_3_fu_1174_p2;
            end if; 
        end if;
    end process;

    slot_row_id_0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_0) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_row_id_0 <= ap_const_lv3_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln80_fu_914_p2 = ap_const_lv1_1))) then 
                slot_row_id_0 <= trunc_ln53_reg_1378;
            end if; 
        end if;
    end process;

    slot_row_id_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_1) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_row_id_1 <= ap_const_lv3_0;
            elsif (((icmp_ln80_1_fu_962_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                slot_row_id_1 <= trunc_ln80_fu_954_p1;
            end if; 
        end if;
    end process;

    slot_row_id_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_2) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_row_id_2 <= ap_const_lv3_0;
            elsif (((icmp_ln80_2_fu_1021_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                slot_row_id_2 <= trunc_ln80_1_fu_1013_p1;
            end if; 
        end if;
    end process;

    slot_row_id_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_3) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_row_id_3 <= ap_const_lv3_0;
            elsif (((icmp_ln80_3_fu_1080_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                slot_row_id_3 <= trunc_ln80_2_fu_1072_p1;
            end if; 
        end if;
    end process;

    slot_row_len_id_0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_0) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_row_len_id_0 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln80_fu_914_p2 = ap_const_lv1_1))) then 
                slot_row_len_id_0 <= add_ln87_fu_929_p2;
            end if; 
        end if;
    end process;

    slot_row_len_id_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_1) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_row_len_id_1 <= ap_const_lv32_0;
            elsif (((icmp_ln80_1_fu_962_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                slot_row_len_id_1 <= add_ln87_1_fu_987_p2;
            end if; 
        end if;
    end process;

    slot_row_len_id_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_2) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_row_len_id_2 <= ap_const_lv32_0;
            elsif (((icmp_ln80_2_fu_1021_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                slot_row_len_id_2 <= add_ln87_2_fu_1046_p2;
            end if; 
        end if;
    end process;

    slot_row_len_id_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln29_fu_692_p1 = ap_const_lv2_3) and (icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                slot_row_len_id_3 <= ap_const_lv32_0;
            elsif (((icmp_ln80_3_fu_1080_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                slot_row_len_id_3 <= add_ln87_3_fu_1105_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                icmp_ln80_1_reg_1425 <= icmp_ln80_1_fu_962_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                icmp_ln80_2_reg_1437 <= icmp_ln80_2_fu_1021_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                icmp_ln80_3_reg_1449 <= icmp_ln80_3_fu_1080_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                icmp_ln80_reg_1413 <= icmp_ln80_fu_914_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_max_row_id_flag_4_phi_fu_584_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state26))) then
                max_row_id <= max_row_id_new_4_reg_560;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                mul_1_i_reg_1576 <= grp_fu_596_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then
                mul_2_i_reg_1584 <= grp_fu_596_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                mul_3_i_reg_1592 <= grp_fu_596_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                mul_i_reg_1558 <= grp_fu_596_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then
                reg_640 <= inp_vec_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state22))) then
                reg_644 <= grp_fu_592_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                trunc_ln107_1_reg_1488 <= trunc_ln107_1_fu_1186_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                trunc_ln107_2_reg_1513 <= trunc_ln107_2_fu_1204_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                trunc_ln107_3_reg_1538 <= trunc_ln107_3_fu_1222_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                trunc_ln107_reg_1473 <= trunc_ln107_fu_1165_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                trunc_ln53_reg_1378 <= trunc_ln53_fu_792_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, cmd_start_read_read_fu_132_p2, ap_CS_fsm_state2, icmp_ln26_fu_658_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (cmd_start_read_read_fu_132_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (cmd_start_read_read_fu_132_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln115_1_fu_1141_p2 <= std_logic_vector(unsigned(empty_16_reg_504) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln115_2_fu_1153_p2 <= std_logic_vector(unsigned(empty_17_reg_549) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln115_3_fu_1174_p2 <= std_logic_vector(unsigned(empty_18_reg_571) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln115_fu_1129_p2 <= std_logic_vector(unsigned(empty_15_reg_459) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln26_fu_652_p2 <= std_logic_vector(unsigned(slot_id_reg_387) + unsigned(ap_const_lv3_1));
    add_ln58_1_fu_887_p2 <= std_logic_vector(unsigned(trunc_ln58_2_fu_883_p1) + unsigned(ap_const_lv3_6));
    add_ln58_fu_825_p2 <= std_logic_vector(unsigned(trunc_ln58_fu_821_p1) + unsigned(ap_const_lv3_2));
    add_ln59_1_fu_836_p2 <= std_logic_vector(unsigned(slot_counter_1) + unsigned(ap_const_lv32_1));
    add_ln59_2_fu_867_p2 <= std_logic_vector(unsigned(slot_counter_2) + unsigned(ap_const_lv32_1));
    add_ln59_3_fu_898_p2 <= std_logic_vector(unsigned(slot_counter_3) + unsigned(ap_const_lv32_1));
    add_ln59_fu_805_p2 <= std_logic_vector(unsigned(slot_counter_0) + unsigned(ap_const_lv32_1));
    add_ln86_1_fu_1094_p2 <= std_logic_vector(unsigned(trunc_ln86_2_fu_1090_p1) + unsigned(ap_const_lv3_6));
    add_ln86_fu_976_p2 <= std_logic_vector(unsigned(trunc_ln86_fu_972_p1) + unsigned(ap_const_lv3_2));
    add_ln87_1_fu_987_p2 <= std_logic_vector(unsigned(slot_row_len_id_1) + unsigned(ap_const_lv32_1));
    add_ln87_2_fu_1046_p2 <= std_logic_vector(unsigned(slot_row_len_id_2) + unsigned(ap_const_lv32_1));
    add_ln87_3_fu_1105_p2 <= std_logic_vector(unsigned(slot_row_len_id_3) + unsigned(ap_const_lv32_1));
    add_ln87_fu_929_p2 <= std_logic_vector(unsigned(slot_row_len_id_0) + unsigned(ap_const_lv32_1));
    add_ln92_1_fu_1005_p2 <= std_logic_vector(unsigned(max_row_id_loc_1_reg_448) + unsigned(ap_const_lv32_1));
    add_ln92_2_fu_1064_p2 <= std_logic_vector(unsigned(max_row_id_loc_2_reg_493) + unsigned(ap_const_lv32_1));
    add_ln92_3_fu_1123_p2 <= std_logic_vector(unsigned(max_row_id_loc_3_reg_538) + unsigned(ap_const_lv32_1));
    add_ln92_fu_946_p2 <= std_logic_vector(unsigned(max_row_id_loc_0_reg_412) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state26 <= ap_CS_fsm(25);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_CS_fsm_state26)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_max_row_id_flag_1_phi_fu_427_p4_assign_proc : process(icmp_ln80_reg_1413, ap_CS_fsm_state8, max_row_id_flag_1_reg_424)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln80_reg_1413 = ap_const_lv1_1))) then 
            ap_phi_mux_max_row_id_flag_1_phi_fu_427_p4 <= ap_const_lv1_1;
        else 
            ap_phi_mux_max_row_id_flag_1_phi_fu_427_p4 <= max_row_id_flag_1_reg_424;
        end if; 
    end process;


    ap_phi_mux_max_row_id_flag_2_phi_fu_473_p4_assign_proc : process(icmp_ln80_1_reg_1425, ap_CS_fsm_state9, max_row_id_flag_2_reg_470)
    begin
        if (((icmp_ln80_1_reg_1425 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_phi_mux_max_row_id_flag_2_phi_fu_473_p4 <= ap_const_lv1_1;
        else 
            ap_phi_mux_max_row_id_flag_2_phi_fu_473_p4 <= max_row_id_flag_2_reg_470;
        end if; 
    end process;


    ap_phi_mux_max_row_id_flag_3_phi_fu_518_p4_assign_proc : process(icmp_ln80_2_reg_1437, ap_CS_fsm_state10, max_row_id_flag_3_reg_515)
    begin
        if (((icmp_ln80_2_reg_1437 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_phi_mux_max_row_id_flag_3_phi_fu_518_p4 <= ap_const_lv1_1;
        else 
            ap_phi_mux_max_row_id_flag_3_phi_fu_518_p4 <= max_row_id_flag_3_reg_515;
        end if; 
    end process;

    ap_phi_mux_max_row_id_flag_4_phi_fu_584_p4 <= max_row_id_flag_4_reg_580;

    ap_phi_mux_max_row_id_loc_1_phi_fu_451_p4_assign_proc : process(icmp_ln80_reg_1413, ap_CS_fsm_state8, add_ln92_fu_946_p2, max_row_id_loc_1_reg_448)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln80_reg_1413 = ap_const_lv1_1))) then 
            ap_phi_mux_max_row_id_loc_1_phi_fu_451_p4 <= add_ln92_fu_946_p2;
        else 
            ap_phi_mux_max_row_id_loc_1_phi_fu_451_p4 <= max_row_id_loc_1_reg_448;
        end if; 
    end process;


    ap_phi_mux_max_row_id_loc_2_phi_fu_496_p4_assign_proc : process(icmp_ln80_1_reg_1425, ap_CS_fsm_state9, add_ln92_1_fu_1005_p2, max_row_id_loc_2_reg_493)
    begin
        if (((icmp_ln80_1_reg_1425 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_phi_mux_max_row_id_loc_2_phi_fu_496_p4 <= add_ln92_1_fu_1005_p2;
        else 
            ap_phi_mux_max_row_id_loc_2_phi_fu_496_p4 <= max_row_id_loc_2_reg_493;
        end if; 
    end process;


    ap_phi_mux_max_row_id_loc_3_phi_fu_541_p4_assign_proc : process(icmp_ln80_2_reg_1437, ap_CS_fsm_state10, add_ln92_2_fu_1064_p2, max_row_id_loc_3_reg_538)
    begin
        if (((icmp_ln80_2_reg_1437 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_phi_mux_max_row_id_loc_3_phi_fu_541_p4 <= add_ln92_2_fu_1064_p2;
        else 
            ap_phi_mux_max_row_id_loc_3_phi_fu_541_p4 <= max_row_id_loc_3_reg_538;
        end if; 
    end process;


    ap_phi_mux_max_row_id_new_1_phi_fu_440_p4_assign_proc : process(icmp_ln80_reg_1413, ap_CS_fsm_state8, add_ln92_fu_946_p2, max_row_id_new_1_reg_436)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln80_reg_1413 = ap_const_lv1_1))) then 
            ap_phi_mux_max_row_id_new_1_phi_fu_440_p4 <= add_ln92_fu_946_p2;
        else 
            ap_phi_mux_max_row_id_new_1_phi_fu_440_p4 <= max_row_id_new_1_reg_436;
        end if; 
    end process;


    ap_phi_mux_max_row_id_new_2_phi_fu_485_p4_assign_proc : process(icmp_ln80_1_reg_1425, ap_CS_fsm_state9, add_ln92_1_fu_1005_p2, max_row_id_new_2_reg_482)
    begin
        if (((icmp_ln80_1_reg_1425 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_phi_mux_max_row_id_new_2_phi_fu_485_p4 <= add_ln92_1_fu_1005_p2;
        else 
            ap_phi_mux_max_row_id_new_2_phi_fu_485_p4 <= max_row_id_new_2_reg_482;
        end if; 
    end process;


    ap_phi_mux_max_row_id_new_3_phi_fu_530_p4_assign_proc : process(icmp_ln80_2_reg_1437, ap_CS_fsm_state10, add_ln92_2_fu_1064_p2, max_row_id_new_3_reg_527)
    begin
        if (((icmp_ln80_2_reg_1437 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_phi_mux_max_row_id_new_3_phi_fu_530_p4 <= add_ln92_2_fu_1064_p2;
        else 
            ap_phi_mux_max_row_id_new_3_phi_fu_530_p4 <= max_row_id_new_3_reg_527;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state26)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln111_1_fu_1217_p1 <= reg_640;
    bitcast_ln111_2_fu_1235_p1 <= reg_640;
    bitcast_ln111_3_fu_1244_p1 <= reg_640;
    bitcast_ln111_fu_1199_p1 <= reg_640;
    bitcast_ln131_1_fu_1304_p1 <= reg_644;
    bitcast_ln131_2_fu_1324_p1 <= reg_644;
    bitcast_ln131_3_fu_1344_p1 <= reg_644;
    bitcast_ln131_fu_1284_p1 <= reg_644;
    cmd_start_read_read_fu_132_p2 <= cmd_start;

    grp_fu_592_p0_assign_proc : process(slot_res_arr_0, slot_res_arr_1, slot_res_arr_2, slot_res_arr_3, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            grp_fu_592_p0 <= slot_res_arr_3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_592_p0 <= slot_res_arr_2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_592_p0 <= slot_res_arr_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_592_p0 <= slot_res_arr_0;
        else 
            grp_fu_592_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_592_p1_assign_proc : process(mul_i_reg_1558, mul_1_i_reg_1576, ap_CS_fsm_state18, mul_2_i_reg_1584, ap_CS_fsm_state19, mul_3_i_reg_1592, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            grp_fu_592_p1 <= mul_3_i_reg_1592;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_592_p1 <= mul_2_i_reg_1584;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_592_p1 <= mul_1_i_reg_1576;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_592_p1 <= mul_i_reg_1558;
        else 
            grp_fu_592_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_596_p0_assign_proc : process(ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, matrix_val_fu_1195_p1, matrix_val_1_fu_1213_p1, matrix_val_2_fu_1231_p1, ap_CS_fsm_state17, matrix_val_3_fu_1240_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            grp_fu_596_p0 <= matrix_val_3_fu_1240_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            grp_fu_596_p0 <= matrix_val_2_fu_1231_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            grp_fu_596_p0 <= matrix_val_1_fu_1213_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            grp_fu_596_p0 <= matrix_val_fu_1195_p1;
        else 
            grp_fu_596_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_596_p1_assign_proc : process(ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, bitcast_ln111_fu_1199_p1, bitcast_ln111_1_fu_1217_p1, bitcast_ln111_2_fu_1235_p1, ap_CS_fsm_state17, bitcast_ln111_3_fu_1244_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            grp_fu_596_p1 <= bitcast_ln111_3_fu_1244_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            grp_fu_596_p1 <= bitcast_ln111_2_fu_1235_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            grp_fu_596_p1 <= bitcast_ln111_1_fu_1217_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            grp_fu_596_p1 <= bitcast_ln111_fu_1199_p1;
        else 
            grp_fu_596_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_624_p2 <= "1" when (slot_arr_row_len_q0 = ap_const_lv32_FFFFFFFF) else "0";
    grp_fu_630_p4 <= slot_data_arr_q0(34 downto 32);
    icmp_ln26_fu_658_p2 <= "1" when (slot_id_reg_387 = ap_const_lv3_4) else "0";
    icmp_ln80_1_fu_962_p2 <= "1" when (slot_row_counter_1 = ap_const_lv32_0) else "0";
    icmp_ln80_2_fu_1021_p2 <= "1" when (slot_row_counter_2 = ap_const_lv32_0) else "0";
    icmp_ln80_3_fu_1080_p2 <= "1" when (slot_row_counter_3 = ap_const_lv32_0) else "0";
    icmp_ln80_fu_914_p2 <= "1" when (slot_row_counter_0 = ap_const_lv32_0) else "0";

    inp_vec_address0_assign_proc : process(ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state12, zext_ln111_fu_1169_p1, zext_ln111_1_fu_1190_p1, zext_ln111_2_fu_1208_p1, zext_ln111_3_fu_1226_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            inp_vec_address0 <= zext_ln111_3_fu_1226_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            inp_vec_address0 <= zext_ln111_2_fu_1208_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            inp_vec_address0 <= zext_ln111_1_fu_1190_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            inp_vec_address0 <= zext_ln111_fu_1169_p1(3 - 1 downto 0);
        else 
            inp_vec_address0 <= "XXX";
        end if; 
    end process;


    inp_vec_ce0_assign_proc : process(ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            inp_vec_ce0 <= ap_const_logic_1;
        else 
            inp_vec_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    matrix_val_1_fu_1213_p1 <= trunc_ln107_1_reg_1488;
    matrix_val_2_fu_1231_p1 <= trunc_ln107_2_reg_1513;
    matrix_val_3_fu_1240_p1 <= trunc_ln107_3_reg_1538;
    matrix_val_fu_1195_p1 <= trunc_ln107_reg_1473;
    or_ln37_fu_677_p2 <= (tmp_fu_664_p3 or ap_const_lv4_1);

    output_vec_address0_assign_proc : process(ap_CS_fsm_state23, ap_CS_fsm_state24, ap_CS_fsm_state25, zext_ln131_fu_1279_p1, zext_ln131_1_fu_1299_p1, zext_ln131_2_fu_1319_p1, zext_ln131_3_fu_1339_p1, ap_CS_fsm_state26)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            output_vec_address0 <= zext_ln131_3_fu_1339_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            output_vec_address0 <= zext_ln131_2_fu_1319_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            output_vec_address0 <= zext_ln131_1_fu_1299_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
            output_vec_address0 <= zext_ln131_fu_1279_p1(3 - 1 downto 0);
        else 
            output_vec_address0 <= "XXX";
        end if; 
    end process;


    output_vec_ce0_assign_proc : process(ap_CS_fsm_state23, ap_CS_fsm_state24, ap_CS_fsm_state25, ap_CS_fsm_state26)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state26) or (ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state23))) then 
            output_vec_ce0 <= ap_const_logic_1;
        else 
            output_vec_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_vec_d0_assign_proc : process(ap_CS_fsm_state23, ap_CS_fsm_state24, ap_CS_fsm_state25, ap_CS_fsm_state26, bitcast_ln131_fu_1284_p1, bitcast_ln131_1_fu_1304_p1, bitcast_ln131_2_fu_1324_p1, bitcast_ln131_3_fu_1344_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            output_vec_d0 <= bitcast_ln131_3_fu_1344_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            output_vec_d0 <= bitcast_ln131_2_fu_1324_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            output_vec_d0 <= bitcast_ln131_1_fu_1304_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
            output_vec_d0 <= bitcast_ln131_fu_1284_p1;
        else 
            output_vec_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_vec_we0_assign_proc : process(ap_CS_fsm_state23, ap_CS_fsm_state24, ap_CS_fsm_state25, ap_CS_fsm_state26)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state26) or (ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state23))) then 
            output_vec_we0 <= ap_const_logic_1;
        else 
            output_vec_we0 <= ap_const_logic_0;
        end if; 
    end process;


    row_len_slot_arr_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state9, tmp_1_fu_683_p3, zext_ln58_fu_800_p1, zext_ln58_2_fu_862_p1, zext_ln86_fu_924_p1, zext_ln86_2_fu_1041_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            row_len_slot_arr_address0 <= zext_ln86_2_fu_1041_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            row_len_slot_arr_address0 <= zext_ln86_fu_924_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_len_slot_arr_address0 <= zext_ln58_2_fu_862_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            row_len_slot_arr_address0 <= zext_ln58_fu_800_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            row_len_slot_arr_address0 <= tmp_1_fu_683_p3(3 - 1 downto 0);
        else 
            row_len_slot_arr_address0 <= "XXX";
        end if; 
    end process;


    row_len_slot_arr_address1_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state10, zext_ln37_fu_672_p1, zext_ln58_1_fu_831_p1, zext_ln58_3_fu_893_p1, zext_ln86_1_fu_982_p1, zext_ln86_3_fu_1100_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            row_len_slot_arr_address1 <= zext_ln86_3_fu_1100_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            row_len_slot_arr_address1 <= zext_ln86_1_fu_982_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            row_len_slot_arr_address1 <= zext_ln58_3_fu_893_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            row_len_slot_arr_address1 <= zext_ln58_1_fu_831_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            row_len_slot_arr_address1 <= zext_ln37_fu_672_p1(3 - 1 downto 0);
        else 
            row_len_slot_arr_address1 <= "XXX";
        end if; 
    end process;


    row_len_slot_arr_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            row_len_slot_arr_ce0 <= ap_const_logic_1;
        else 
            row_len_slot_arr_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    row_len_slot_arr_ce1_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            row_len_slot_arr_ce1 <= ap_const_logic_1;
        else 
            row_len_slot_arr_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    row_len_slot_arr_d0_assign_proc : process(slot_arr_row_len_q0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            row_len_slot_arr_d0 <= slot_arr_row_len_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            row_len_slot_arr_d0 <= ap_const_lv32_0;
        else 
            row_len_slot_arr_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    row_len_slot_arr_d1_assign_proc : process(slot_arr_row_len_q0, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            row_len_slot_arr_d1 <= slot_arr_row_len_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            row_len_slot_arr_d1 <= ap_const_lv32_0;
        else 
            row_len_slot_arr_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    row_len_slot_arr_we0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, icmp_ln26_fu_658_p2, grp_fu_624_p2)
    begin
        if ((((grp_fu_624_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((grp_fu_624_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            row_len_slot_arr_we0 <= ap_const_logic_1;
        else 
            row_len_slot_arr_we0 <= ap_const_logic_0;
        end if; 
    end process;


    row_len_slot_arr_we1_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state7, icmp_ln26_fu_658_p2, grp_fu_624_p2)
    begin
        if ((((grp_fu_624_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((grp_fu_624_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln26_fu_658_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            row_len_slot_arr_we1 <= ap_const_logic_1;
        else 
            row_len_slot_arr_we1 <= ap_const_logic_0;
        end if; 
    end process;


    slot_arr_row_len_address0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            slot_arr_row_len_address0 <= ap_const_lv64_3(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            slot_arr_row_len_address0 <= ap_const_lv64_2(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            slot_arr_row_len_address0 <= ap_const_lv64_1(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            slot_arr_row_len_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        else 
            slot_arr_row_len_address0 <= "XX";
        end if; 
    end process;


    slot_arr_row_len_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            slot_arr_row_len_ce0 <= ap_const_logic_1;
        else 
            slot_arr_row_len_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    slot_data_arr_address0_assign_proc : process(ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            slot_data_arr_address0 <= ap_const_lv64_3(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            slot_data_arr_address0 <= ap_const_lv64_2(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            slot_data_arr_address0 <= ap_const_lv64_1(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            slot_data_arr_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        else 
            slot_data_arr_address0 <= "XX";
        end if; 
    end process;


    slot_data_arr_ce0_assign_proc : process(ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            slot_data_arr_ce0 <= ap_const_logic_1;
        else 
            slot_data_arr_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_683_p3 <= (ap_const_lv60_0 & or_ln37_fu_677_p2);
    tmp_fu_664_p3 <= (slot_id_reg_387 & ap_const_lv1_0);
    trunc_ln107_1_fu_1186_p1 <= slot_data_arr_q0(32 - 1 downto 0);
    trunc_ln107_2_fu_1204_p1 <= slot_data_arr_q0(32 - 1 downto 0);
    trunc_ln107_3_fu_1222_p1 <= slot_data_arr_q0(32 - 1 downto 0);
    trunc_ln107_fu_1165_p1 <= slot_data_arr_q0(32 - 1 downto 0);
    trunc_ln29_fu_692_p1 <= slot_id_reg_387(2 - 1 downto 0);
    trunc_ln53_fu_792_p1 <= max_row_id_loc_0_reg_412(3 - 1 downto 0);
    trunc_ln58_1_fu_852_p1 <= slot_counter_2(3 - 1 downto 0);
    trunc_ln58_2_fu_883_p1 <= slot_counter_3(3 - 1 downto 0);
    trunc_ln58_fu_821_p1 <= slot_counter_1(3 - 1 downto 0);
    trunc_ln80_1_fu_1013_p1 <= ap_phi_mux_max_row_id_loc_2_phi_fu_496_p4(3 - 1 downto 0);
    trunc_ln80_2_fu_1072_p1 <= ap_phi_mux_max_row_id_loc_3_phi_fu_541_p4(3 - 1 downto 0);
    trunc_ln80_fu_954_p1 <= ap_phi_mux_max_row_id_loc_1_phi_fu_451_p4(3 - 1 downto 0);
    trunc_ln86_1_fu_1031_p1 <= slot_row_len_id_2(3 - 1 downto 0);
    trunc_ln86_2_fu_1090_p1 <= slot_row_len_id_3(3 - 1 downto 0);
    trunc_ln86_fu_972_p1 <= slot_row_len_id_1(3 - 1 downto 0);
    xor_ln58_fu_856_p2 <= (trunc_ln58_1_fu_852_p1 xor ap_const_lv3_4);
    xor_ln86_fu_1035_p2 <= (trunc_ln86_1_fu_1031_p1 xor ap_const_lv3_4);
    zext_ln111_1_fu_1190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_630_p4),64));
    zext_ln111_2_fu_1208_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_630_p4),64));
    zext_ln111_3_fu_1226_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_630_p4),64));
    zext_ln111_fu_1169_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_630_p4),64));
    zext_ln131_1_fu_1299_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(slot_row_id_1),64));
    zext_ln131_2_fu_1319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(slot_row_id_2),64));
    zext_ln131_3_fu_1339_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(slot_row_id_3),64));
    zext_ln131_fu_1279_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(slot_row_id_0),64));
    zext_ln37_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_664_p3),64));
    zext_ln58_1_fu_831_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln58_fu_825_p2),64));
    zext_ln58_2_fu_862_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln58_fu_856_p2),64));
    zext_ln58_3_fu_893_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln58_1_fu_887_p2),64));
    zext_ln58_fu_800_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(slot_counter_0),64));
    zext_ln86_1_fu_982_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln86_fu_976_p2),64));
    zext_ln86_2_fu_1041_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln86_fu_1035_p2),64));
    zext_ln86_3_fu_1100_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln86_1_fu_1094_p2),64));
    zext_ln86_fu_924_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(slot_row_len_id_0),64));
end behav;
