#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_local_block", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_local_deadlock", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("out_r", 32, hls_out, 0, "ap_ovld", "out_data", 1),
	Port_Property("out_r_ap_vld", 1, hls_out, 0, "ap_ovld", "out_vld", 1),
	Port_Property("subrow_vals", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("subrow_col_indices", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("mult_enables_address0", 2, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("mult_enables_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("mult_enables_q0", 1, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("label_r", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("init_vector", 1, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("vector_0", 32, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("vector_1", 32, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("vector_2", 32, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("vector_3", 32, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("vector_4", 32, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("vector_5", 32, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("vector_6", 32, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("vector_7", 32, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("vector_8", 32, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("vector_9", 32, hls_in, 15, "ap_none", "in_data", 1),
	Port_Property("vector_10", 32, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("vector_11", 32, hls_in, 17, "ap_none", "in_data", 1),
	Port_Property("vector_12", 32, hls_in, 18, "ap_none", "in_data", 1),
	Port_Property("vector_13", 32, hls_in, 19, "ap_none", "in_data", 1),
	Port_Property("vector_14", 32, hls_in, 20, "ap_none", "in_data", 1),
	Port_Property("vector_15", 32, hls_in, 21, "ap_none", "in_data", 1),
	Port_Property("vector_16", 32, hls_in, 22, "ap_none", "in_data", 1),
	Port_Property("vector_17", 32, hls_in, 23, "ap_none", "in_data", 1),
	Port_Property("vector_18", 32, hls_in, 24, "ap_none", "in_data", 1),
	Port_Property("vector_19", 32, hls_in, 25, "ap_none", "in_data", 1),
	Port_Property("vector_20", 32, hls_in, 26, "ap_none", "in_data", 1),
	Port_Property("vector_21", 32, hls_in, 27, "ap_none", "in_data", 1),
	Port_Property("vector_22", 32, hls_in, 28, "ap_none", "in_data", 1),
	Port_Property("out_r_ap_lwr", 1, hls_out, 0, "ap_ovld", "out_lwr", 1),
};
const char* HLS_Design_Meta::dut_name = "accelerate";
